import type { ThemeConfig } from 'antd';

export const themeConfig: ThemeConfig = {
  cssVar: true,
  hashed: true,
  token: {
    colorPrimary:        '#18181b',
    colorInfo:           '#0ea5e9',
    colorSuccess:        '#059669',
    colorWarning:        '#d97706',
    colorError:          '#dc2626',
    colorTextBase:       '#18181b',
    colorBgBase:         '#ffffff',
    colorBgLayout:       '#fafafa',
    colorBorder:         '#e4e4e7',
    colorBorderSecondary:'#f4f4f5',
    borderRadius:        6,
    borderRadiusSM:      4,
    borderRadiusLG:      8,
    fontFamily:          "'Inter', ui-sans-serif, system-ui, sans-serif",
    fontSize:            13,
    fontSizeHeading1:    24,
    fontSizeHeading2:    20,
    fontSizeHeading3:    16,
    controlHeight:       32,
    controlHeightSM:     28,
    sizeUnit:            4,
    sizeStep:            4,
    wireframe:           false,
  },
  components: {
    Layout: {
      headerBg:          '#ffffff',
      headerHeight:      56,
      headerPadding:     '0 24px',
      siderBg:           '#18181b',
      bodyBg:            '#fafafa',
      footerBg:          '#fafafa',
    },
    Menu: {
      darkItemBg:                '#18181b',
      darkItemSelectedBg:        '#27272a',
      darkItemHoverBg:           '#27272a',
      darkSubMenuItemBg:         '#18181b',
      darkItemColor:             '#a1a1aa',
      darkItemSelectedColor:     '#fafafa',
      darkItemHoverColor:        '#fafafa',
      darkGroupTitleColor:       '#52525b',
      itemMarginInline:          8,
      itemBorderRadius:          4,
      itemHeight:                36,
      collapsedIconSize:         16,
    },
    Card: {
      headerBg:          'transparent',
      headerHeight:      44,
      headerHeightSM:    40,
      bodyPadding:       16,
      paddingLG:         16,
    },
    Table: {
      headerBg:          '#fafafa',
      headerColor:       '#52525b',
      rowHoverBg:        '#fafafa',
      cellPaddingBlock:  10,
      cellPaddingInline: 12,
      borderColor:       '#f4f4f5',
    },
    Statistic: {
      titleFontSize:    11,
      contentFontSize:  28,
    },
    Tag: {
      defaultBg:    '#f4f4f5',
      defaultColor: '#3f3f46',
    },
    Button: {
      controlHeight:    32,
      controlHeightSM:  28,
      borderRadius:     6,
    },
    Form: {
      labelFontSize:    12,
    },
  },
};
